# The machine name of the group, by which it is referenced in individual
# migrations.
id: users

# A human-friendly label for the group.
label: Users, accounts and roles

# More information about the group.
description: User account related migrations.

source_type: Custom tables

# Key is a source DB key from settings.php, e.g.: $databases['source_db']['default'] = [...].
shared_configuration:
  source:
    key: source_db
